# A build that is triggered nightly if there are new changes in the last 24 hours.
# This is useful for dev builds for internal testing.

name: "nightly build"
on:
  schedule:
    - cron: "0 2 * * *"

env:
  # The Godot Version you want to use.
  # IMPORTANT: You also have to manually set the image tag in the export job to the same version!
  GODOT_VERSION: 4.3.dev6
  # The name of your export file (for example your game)
  EXPORT_NAME: AwesomeGameName

jobs:
  # Checks if there is a change in the repository
  check:
    name: check-changes
    runs-on: ubuntu-22.04
    outputs:
      changes: ${{ steps.nightly-check.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - id: nightly-check
        name: Check for changes since 24 hours
        shell: bash
        # Change the 24hours to any time to you like, for example 3days
        run: '([ $(git rev-list --after="24hours" ${{ github.sha }} | wc -l) -ge 1 ] && echo "changes=true"  || echo "changes=false") >> $GITHUB_OUTPUT'
      - name: has_changed
        shell: bash
        run: echo ${{ steps.nightly-check.outputs.changes }}

  export:
    # Run only if there are changes in the last 24 hours
    needs: check
    if: ${{ needs.check.outputs.changes == 'true' }}
    strategy:
      # You can increase this, especially useful for private github runner
      max-parallel: 1
      matrix:
        # Add your environent to this list. Your project must have the corrospending template name
        environment:
          [
            {
              godot_template: "Windows Desktop x86",
              output_dir: windows_x86,
              file_suffix: "exe",
              os: windows,
              architecture: x86,
            },
            {
              godot_template: "Linux x86",
              output_dir: linux_x86,
              file_suffix: "x86_64",
              os: linux,
              architecture: x86,
            },
            {
              godot_template: "Linux arm64",
              output_dir: linux_arm64,
              file_suffix: "arm64",
              os: linux,
              architecture: arm64,
            },
          ]
    runs-on: ubuntu-22.04
    container:
      # Change this image to the version you want
      # We can't use a variable here because the context is not available
      # at this part of the action
      image: ghcr.io/meldanor/godot-ci:4.3-dev6-minimal
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Godot Tempaltes
        # This step is necessary because the GitHub runner overrides the root directory from the image
        # and deletes the export templates -> so we relink them again
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          ln -sf /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
      - name: Build
        run: |
          mkdir -p build/${{matrix.environment.output_dir}}
          godot --headless --verbose --export-release "${{matrix.environment.godot_template}}" build/${{matrix.environment.output_dir}}/$EXPORT_NAME.${{matrix.environment.file_suffix}}
          cd build/${{matrix.environment.output_dir}}
          zip $EXPORT_NAME.zip *
      - name: Upload
        run: echo "Your Upload. You have cURL, rsync and butler (itch.io) in this docker"
